# Generated by Django 3.1.4 on 2022-03-22 15:55

from django.db import migrations, models
import django.db.models.deletion
import lesson_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('homeworkinfo', models.CharField(max_length=300, null=True, verbose_name='homeworkinfo')),
                ('attach_file_exist', models.BooleanField(default=False, verbose_name='attach_file_exist')),
                ('start_time', models.DateField(default='1900-01-01', verbose_name='start_time')),
                ('finish_time', models.DateField(default='9999-12-31', verbose_name='finish_time')),
                ('turn_it_available', models.BooleanField(default=False, verbose_name='turn_it_available')),
            ],
            options={
                'db_table': 'homework',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lessonid', models.AutoField(help_text='課程ID編號，自動產生', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='課程名稱', max_length=45)),
                ('lessontype', models.CharField(help_text='課程種類', max_length=45)),
                ('auth', models.IntegerField(default=0, help_text='建立者')),
                ('situation', models.CharField(help_text='實體、線上或兩者皆有', max_length=15)),
                ('verify', models.BooleanField(default=False, help_text='審查參加人員')),
                ('annouce_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('lessoninfo', models.CharField(max_length=300)),
                ('certificate', models.BooleanField(default=False)),
                ('address', models.CharField(default='online mode', max_length=300)),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='Studentlist',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('student_id', models.IntegerField(verbose_name='student_id')),
                ('first_name', models.CharField(max_length=150, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last_name')),
                ('lesson_situation', models.CharField(max_length=150, null=True, verbose_name='lesson_situation')),
                ('agree', models.BooleanField(default=True, verbose_name='agree')),
                ('join_reason', models.CharField(max_length=300, null=True, verbose_name='join_reason')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
            options={
                'db_table': 'lesson_studentlist',
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('cover', models.BooleanField(default=False, verbose_name='cover')),
                ('textbook', models.BooleanField(default=False, verbose_name='textbook')),
                ('media_type', models.IntegerField(help_text='file:0 picture:1 vided:2', verbose_name='media_type')),
                ('file', models.FileField(null=True, upload_to=lesson_app.models.path_return, verbose_name='file')),
                ('image', models.ImageField(null=True, upload_to=lesson_app.models.path_return, verbose_name='image')),
                ('external_source', models.CharField(max_length=500, null=True, verbose_name='external_source')),
                ('filename', models.CharField(max_length=150, verbose_name='filename')),
                ('open_access', models.BooleanField(default=True, verbose_name='open_access')),
                ('only_for_members', models.BooleanField(default=True, verbose_name='only_for_members')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
            options={
                'db_table': 'lesson_multimedia',
            },
        ),
        migrations.CreateModel(
            name='LessonTable',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('ch', models.IntegerField(default=0)),
                ('sb', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=150, null=True)),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
            ],
            options={
                'db_table': 'lesson_table',
            },
        ),
        migrations.CreateModel(
            name='LessonRelatedMedia',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_id', models.IntegerField()),
                ('media_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.multimedia')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lessontable')),
            ],
            options={
                'db_table': 'lesson_related_media',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmit',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('submitinfo', models.CharField(max_length=300, null=True, verbose_name='submitinfo')),
                ('attach_file_exist', models.BooleanField(default=False, verbose_name='attach_file_exist')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='submit_time')),
                ('score', models.IntegerField(null=True, verbose_name='score')),
                ('homework_id', models.ForeignKey(default=-9, on_delete=django.db.models.deletion.CASCADE, to='lesson_app.homework', verbose_name='homework_id')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
                ('lessontable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lessontable', verbose_name='lesson_table_id')),
            ],
            options={
                'db_table': 'homeworksubmit',
            },
        ),
        migrations.CreateModel(
            name='HomeworkFileTable',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('file', models.FileField(null=True, upload_to=lesson_app.models.homework_submit_file_path_return, verbose_name='file')),
                ('open_access', models.BooleanField(default=False, verbose_name='open_access')),
                ('only_for_members', models.BooleanField(default=False, verbose_name='only_for_members')),
                ('homeworksubmit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson_app.homeworksubmit', verbose_name='homeworksubmit_id')),
                ('lesson_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id')),
                ('lessontable_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lessontable', verbose_name='lesson_table_id')),
            ],
            options={
                'db_table': 'homeworkfiletable',
            },
        ),
        migrations.CreateModel(
            name='HomeworkAttachFile',
            fields=[
                ('inner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='inner_id')),
                ('file', models.FileField(null=True, upload_to=lesson_app.models.homework_file_path_return, verbose_name='file')),
                ('open_access', models.BooleanField(default=False, verbose_name='open_access')),
                ('only_for_members', models.BooleanField(default=False, verbose_name='only_for_members')),
                ('homeworkid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.homework', verbose_name='homework_id')),
            ],
            options={
                'db_table': 'homework_attach_file',
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lesson', verbose_name='lesson_id'),
        ),
        migrations.AddField(
            model_name='homework',
            name='lessontable_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_app.lessontable', verbose_name='lesson_table_id'),
        ),
    ]
