version: "3"
services:
 nginx_server:
  container_name: nginx_server
  restart: always
  build: ./nginx_conf
  volumes: 
   - ./elearning_test:/webcode
  ports:
   - "8000:80"
  expose:
   - "8000"
  links: 
   - django_sevice
  depends_on: 
   - django_sevice
  environment:
   TZ: Asia/Taipei
 
 
 django_sevice:
  container_name: django_elearning_root
  build: ./elearning_test
  restart: always
  depends_on: 
   - mysql_server_elearning
  expose:
   - "8001"
  volumes: 
   # 映射elearning_test下所有資料至docker下的 webcode資料夾
   - ./elearning_test:/webcode
  environment:
   -TZ: Asia/Taipei
  tty: true

 
 # mysql
 mysql_server:
  container_name: mysql_server_elearning
  image: mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: tt123
   MYSQL_TCP_PORT: 33061
   TZ: Asia/Taipei
  volumes:
   - ./mysql:/docker-entrypoint-initdb.d
  ports:
   - "33061:33061"


   #https://zhuanlan.zhihu.com/p/145364353